### ISSUE TITLE
Book Translation in Chinese

### ISSUE THREAD

**Issue by hanyuancheung** [gitops-tech/book#3]
Hi, I've read this book which is about GitOps and continuous deployment. It's quite a great book that helps me a lot in GitOps practice. And I would like to ask if you have any plans to translate this book into Chinese, cause this may help more and more readers learn this area as well as help to expand the influence of itself. Thanks. @florian-beetz

**Comment by florian-beetz** [comment]
Hi, thank you for your feedback. It's great to hear that our book has helped you!

However, we currently don't have any plans for releasing a Chinese version of the book, as neither I nor @anjakammer nor @simonharrer speak Chinese.

**Comment by hanyuancheung** [comment]
> Hi, thank you for your feedback. It's great to hear that our book has helped you!
> 
> However, we currently don't have any plans for releasing a Chinese version of the book, as neither I nor @anjakammer nor @simonharrer speak Chinese.

Ok, I see. If you have any plans later, It's my pleasure to do the translation job and something like that.
